language: java


jdk:
	- oraclejdk8
	- oraclejdk9
	- openjdk8

addons:
  sonarcloud:
    organization: "fouad-e-github" # the key of the org you chose at step #3
    token:
      secure: feac9db81826745a508882145fce6744447a3997 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
